### ISSUE TITLE
Trade Macro Doesn't Respond to Alt+D

### ISSUE THREAD

**Issue by Zerfaul** [PoE-TradeMacro/POE-TradeMacro#1176]
Hi. My trademacro doesnt respond to alt+D or any price related keys. 
When i press to F5 i can go to my hideout or when i press Alt + E it responds. So its working but not responding Alt+D
I'm running the game Borderless windowed and got latest AHK and Trademacro.
Thanks.

_TEMPLATE_ (Remove the explanations here from your post) 

Make sure:
* That you have checked the Wiki/FAQ before creating any issue.
* That poe.trade/GGG's website don't have any issues if loading the script takes too long or failes.

Information to include:
* AHK (including 32/64bit) version if you have any kind of script errors.
* Windows version could be relevant.

Fill out everything that may be relevant and remove everything except these informations below:  

AHK version:latest
Windows version:win10

**Comment by Eakz** [comment]
I have same issue. Was trying to find the solution. Doesnt respond to anything besides alt+e(which again shows me that "no account name specified in settings menu")...Prices not working at all

**Comment by derbol** [comment]
Same here, most keybinds don't show anything.
When saving the information to the clipboard, I can see, that it does correctly fetch everything, it just doesn't display anything.
I reinstalled to ahk 1.33 64 bit, deleted all old trade macro folders and backups, still the same.
F5 etc works, is functioning, just not displaying anything most of the time.

**Comment by Zenthae** [comment]
broken for me too

**Comment by Uchigatan** [comment]
Bump

**Comment by Spykerr2842** [comment]
Same here. F5 works and Alt+E and not much else. Tried reinstalling everything, nothing changed

**Comment by ATufekovic** [comment]
Bump, same issues as other people, i thought i was crazy for a moment and that i broke something before looking the issue up.

**Comment by soockee** [comment]
same

**Comment by Zenthae** [comment]
well, anyway, since it's been month since the last update we probably won't have a fix, time to use something else

**Comment by arsirantala** [comment]
Same here - doesn't work. Also reinstalled treade macro, but didn't change the expected behavior.

**Comment by serogich** [comment]
and it doesn't work for me

**Comment by ba-chan** [comment]
It's not just Alt+D, it seems to be anything that requires parsing of the item text copied from the game client.  The format has changed slightly, meaning it can no longer be cut-n-pasted into Path of Building without editing either.

**Comment by froks** [comment]
Pull Request #1177 should fix at least simple cases

**Comment by Zenthae** [comment]
if anyone interested, i found this https://github.com/Kyusung4698/PoE-Overlay as an alternative, sadly it depends on Overwolf, but at least it do the job

**Comment by Zerfaul** [comment]
> if anyone interested, i found this https://github.com/Kyusung4698/PoE-Overlay as an alternative, sadly it depends on Overwolf, but at least it do the job

Ah i didn't know this one. Thank you for sharing

**Comment by serlucian** [comment]
same for me. ald+d not working, just alt+e ;(

**Comment by Almighty1g** [comment]
Same.

**Comment by Spykerr2842** [comment]
> if anyone interested, i found this https://github.com/Kyusung4698/PoE-Overlay as an alternative, sadly it depends on Overwolf, but at least it do the job

https://github.com/SnosMe/awakened-poe-trade This is what I'm trying since yesterday. Pretty positive so far

**Comment by dwiggins5091** [comment]
bump

**Comment by xkylieo** [comment]
Theres a fix someone posted elsewhere had to edit some code at Line 7350

leaving my copy of the fixed version if youd like.
https://www.dropbox.com/s/l2qlh4vppwbs06l/POE-ItemInfo.ahk?dl=0

; ParseItemName fixed by user: uldo_.  Thanks!
ParseItemName(ItemDataChunk, ByRef ItemName, ByRef ItemBaseName, AffixCount = "", ItemData = "")
{
isVaalGem := false
If (RegExMatch(Trim([ItemData.Parts](https://ItemData.Parts)\[1\]), "i)\^Rarity: Gem") and RegExMatch(Trim([ItemData.Parts](https://ItemData.Parts)\[2\]), "i)Vaal")) {

	isVaalGem := true
}

If (RegExMatch(ItemData.NamePlate, "i)Rarity\\s?+:\\s?+(Currency|Divination Card|Gem)", match)) {
If (RegExMatch(match1, "i)Gem")) {
	ItemBaseName := Trim(RegExReplace(ItemName, "i) Support"))
} Else {

	ItemBaseName := Trim(ItemName)

}		
}
ItemDataChunk := SubStr(ItemDataChunk, InStr(ItemDataChunk,"`n") + 1)    ;   <----- new

**Comment by KingKatura** [comment]
> Theres a fix someone posted elsewhere had to edit some code at Line 7350
> 
> leaving my copy of the fixed version if youd like.
> https://www.dropbox.com/s/l2qlh4vppwbs06l/POE-ItemInfo.ahk?dl=0
> 
> ; ParseItemName fixed by user: uldo_. Thanks!
> ParseItemName(ItemDataChunk, ByRef ItemName, ByRef ItemBaseName, AffixCount = "", ItemData = "")
> {
> isVaalGem := false
> If (RegExMatch(Trim([ItemData.Parts](https://ItemData.Parts)[1]), "i)^Rarity: Gem") and RegExMatch(Trim([ItemData.Parts](https://ItemData.Parts)[2]), "i)Vaal")) {
> 
> ```
> isVaalGem := true
> ```
> 
> }
> 
> If (RegExMatch(ItemData.NamePlate, "i)Rarity\s?+:\s?+(Currency|Divination Card|Gem)", match)) {
> If (RegExMatch(match1, "i)Gem")) {
> ItemBaseName := Trim(RegExReplace(ItemName, "i) Support"))
> } Else {
> 
> ```
> ItemBaseName := Trim(ItemName)
> ```
> 
> }
> }
> ItemDataChunk := SubStr(ItemDataChunk, InStr(ItemDataChunk,"`n") + 1) ; <----- new

hey it works.. drag into poemacro-resources-AHk and overwrite it will work again. Thanks for the fix  now the creator needs to update it.

**Comment by ArensKyle** [comment]
> 
> 
> > Theres a fix someone posted elsewhere had to edit some code at Line 7350
> > leaving my copy of the fixed version if youd like.
> > https://www.dropbox.com/s/l2qlh4vppwbs06l/POE-ItemInfo.ahk?dl=0
> > ; ParseItemName fixed by user: uldo_. Thanks!
> > ParseItemName(ItemDataChunk, ByRef ItemName, ByRef ItemBaseName, AffixCount = "", ItemData = "")
> > {
> > isVaalGem := false
> > If (RegExMatch(Trim([ItemData.Parts](https://ItemData.Parts)[1]), "i)^Rarity: Gem") and RegExMatch(Trim([ItemData.Parts](https://ItemData.Parts)[2]), "i)Vaal")) {
> > ```
> > isVaalGem := true
> > ```
> > 
> > 
> > }
> > If (RegExMatch(ItemData.NamePlate, "i)Rarity\s?+:\s?+(Currency|Divination Card|Gem)", match)) {
> > If (RegExMatch(match1, "i)Gem")) {
> > ItemBaseName := Trim(RegExReplace(ItemName, "i) Support"))
> > } Else {
> > ```
> > ItemBaseName := Trim(ItemName)
> > ```
> > 
> > 
> > }
> > }
> > ItemDataChunk := SubStr(ItemDataChunk, InStr(ItemDataChunk,"`n") + 1) ; <----- new
> 
> hey it works.. drag into poemacro-resources-AHk and overwrite it will work again. Thanks for the fix now the creator needs to update it.

Looks like this fixes the basic search functionality, but I'm still unable to run an advanced search on rare items. Anyone have ideas where that might be broken?

**Comment by ArensKyle** [comment]
> Looks like this fixes the basic search functionality, but I'm still unable to run an advanced search on rare items. Anyone have ideas where that might be broken?

Replying to my own comment, it actually looks like the item type parsing is what's busted. Advanced search will still work on weapons, but it *only* works on weapons. You can hack around it by setting the property "hasAdvancedSearch" to always be true instead of having it actually check. That change is in POE-TradeMacro-2.16.0\resources\ahk\TradeMacro.ahk on line 468.

**Comment by Nivelm** [comment]
New fix in this post https://github.com/PoE-TradeMacro/POE-TradeMacro/pull/1177#issuecomment-822774321

Just add this line to an original https://github.com/PoE-TradeMacro/POE-TradeMacro/blob/eb20d12d1dc875c0bde6731d8b8193031309bffa/resources/ahk/POE-ItemInfo.ahk
 
Now advanced search works.

**Comment by ba-chan** [comment]
> New fix in this post [#1177 (comment)](https://github.com/PoE-TradeMacro/POE-TradeMacro/pull/1177#issuecomment-822774321)

Nice, all my use cases are now functional :-)

**Comment by CountWiggin** [comment]
@Nivelm : Hi, I'm having trouble fixing TradeMacro using your instructions - if I add that specific line ("https://github.com/PoE-TradeMacro/POE-TradeMacro/blob/eb20d12d1dc875c0bde6731d8b8193031309bffa/resources/ahk/POE-ItemInfo.ahk") to the file POE-ItemInfo.ahk I get an error while launching, if I get all the code lines from here (https://github.com/PoE-TradeMacro/POE-TradeMacro/blob/eb20d12d1dc875c0bde6731d8b8193031309bffa/resources/ahk/POE-ItemInfo.ahk) and I add them in the file (have no ideea where to add them) I also get an error while launching, if I get the code lines mentioned above and replace all content in the POE-ItemInfo.ahk I can launch it but advanced search doesn't work. I play Standard league, softcore, windowed.  
Can you please explain step-by-step what I need to do in order to make it work ? Tx.

**Comment by Nivelm** [comment]
> 
> 
> @nivlem : Hi, I'm having trouble fixing TradeMacro using your instructions - if I add that specific line ("https://github.com/PoE-TradeMacro/POE-TradeMacro/blob/eb20d12d1dc875c0bde6731d8b8193031309bffa/resources/ahk/POE-ItemInfo.ahk") to the file POE-ItemInfo.ahk I get an error while launching, if I get all the code lines from here (https://github.com/PoE-TradeMacro/POE-TradeMacro/blob/eb20d12d1dc875c0bde6731d8b8193031309bffa/resources/ahk/POE-ItemInfo.ahk) and I add them in the file (have no ideea where to add them) I also get an error while launching, if I get the code lines mentioned above and replace all content in the POE-ItemInfo.ahk I can launch it but advanced search doesn't work. I play Standard league, softcore, windowed.
> Can you please explain step-by-step what I need to do in order to make it work ? Tx.

First of all you need the original file from your installation with no modifications. You can extract and replace it from your downloaded POE-TradeMacro-2.16.0.zip

Go find in your PC where POE-TradeMacro is installed. Folder should be POE-TradeMacro-2.16.0

Inside POE-TradeMacro-2.16.0 folder open resources\ then ahk\       

Locate POE-ItemInfo.ahk file

Open it with Notepad

Find this function: PreProcessContents (Menu-Edit-Find)

```
PreProcessContents(CBContents)
{
; --- Place fixes for data inconsistencies here ---

; Remove the line that indicates an item cannot be used due to missing character stats	
	; Matches "Rarity: ..." + anything until "--------"\r\n
	If (RegExMatch(CBContents, "s)^(.+?:.+?\r\n)(.+?-{8}\r\n)(.*)", match)) {
```

Add this new line:
```
CBContents:= SubStr(CBContents, InStr(CBContents,"`n") + 1) 
```

Function should look like this with the new added line:
```
PreProcessContents(CBContents)
{
; --- Place fixes for data inconsistencies here ---
CBContents:= SubStr(CBContents, InStr(CBContents,"`n") + 1) ; <----- new

; Remove the line that indicates an item cannot be used due to missing character stats	
	; Matches "Rarity: ..." + anything until "--------"\r\n
	If (RegExMatch(CBContents, "s)^(.+?:.+?\r\n)(.+?-{8}\r\n)(.*)", match)) {
```

Save file and restart POETradeMacro.

**Comment by nesreb** [comment]
@Nivelm, I edited the file and added the single line of code you suggested.  Everything's working so far.  Thank you for generously volunteering your time to help your fellow PoE addicts.

**Comment by CountWiggin** [comment]
@Nivelm : Thank you for helping, it worked !. Have a nice day :)

**Comment by xkylieo** [comment]
> > > Theres a fix someone posted elsewhere had to edit some code at Line 7350
> > > leaving my copy of the fixed version if youd like.
> > > https://www.dropbox.com/s/l2qlh4vppwbs06l/POE-ItemInfo.ahk?dl=0
> > > ; ParseItemName fixed by user: uldo_. Thanks!
> > > ParseItemName(ItemDataChunk, ByRef ItemName, ByRef ItemBaseName, AffixCount = "", ItemData = "")
> > > {
> > > isVaalGem := false
> > > If (RegExMatch(Trim([ItemData.Parts](https://ItemData.Parts)[1]), "i)^Rarity: Gem") and RegExMatch(Trim([ItemData.Parts](https://ItemData.Parts)[2]), "i)Vaal")) {
> > > ```
> > > isVaalGem := true
> > > ```
> > > 
> > > 
> > > }
> > > If (RegExMatch(ItemData.NamePlate, "i)Rarity\s?+:\s?+(Currency|Divination Card|Gem)", match)) {
> > > If (RegExMatch(match1, "i)Gem")) {
> > > ItemBaseName := Trim(RegExReplace(ItemName, "i) Support"))
> > > } Else {
> > > ```
> > > ItemBaseName := Trim(ItemName)
> > > ```
> > > 
> > > 
> > > }
> > > }
> > > ItemDataChunk := SubStr(ItemDataChunk, InStr(ItemDataChunk,"`n") + 1) ; <----- new
> > 
> > 
> > hey it works.. drag into poemacro-resources-AHk and overwrite it will work again. Thanks for the fix now the creator needs to update it.
> 
> Looks like this fixes the basic search functionality, but I'm still unable to run an advanced search on rare items. Anyone have ideas where that might be broken?

Fixed now new download link
https://www.dropbox.com/s/l2qlh4vppwbs06l/POE-ItemInfo.ahk?dl=0

**Comment by Herbie-pat** [comment]
Just made an account to say you:
Thank you for your excellent work!
I also got worried what could have gone wrong and i often have my issues with diving into solving problems like this. I also want to thank you in behalf of my friends who also use this tool and don't have to worry and just add the script line and enjoy playing <3

**Comment by MorbiusProductions** [comment]
> > @nivlem : Hi, I'm having trouble fixing TradeMacro using your instructions - if I add that specific line ("https://github.com/PoE-TradeMacro/POE-TradeMacro/blob/eb20d12d1dc875c0bde6731d8b8193031309bffa/resources/ahk/POE-ItemInfo.ahk") to the file POE-ItemInfo.ahk I get an error while launching, if I get all the code lines from here (https://github.com/PoE-TradeMacro/POE-TradeMacro/blob/eb20d12d1dc875c0bde6731d8b8193031309bffa/resources/ahk/POE-ItemInfo.ahk) and I add them in the file (have no ideea where to add them) I also get an error while launching, if I get the code lines mentioned above and replace all content in the POE-ItemInfo.ahk I can launch it but advanced search doesn't work. I play Standard league, softcore, windowed.
> > Can you please explain step-by-step what I need to do in order to make it work ? Tx.
> 
> First of all you need the original file from your installation with no modifications. You can extract and replace it from your downloaded POE-TradeMacro-2.16.0.zip
> 
> Go find in your PC where POE-TradeMacro is installed. Folder should be POE-TradeMacro-2.16.0
> 
> Inside POE-TradeMacro-2.16.0 folder open resources\ then ahk\
> 
> Locate POE-ItemInfo.ahk file
> 
> Open it with Notepad
> 
> Find this function: PreProcessContents (Menu-Edit-Find)
> 
> ```
> PreProcessContents(CBContents)
> {
> ; --- Place fixes for data inconsistencies here ---
> 
> ; Remove the line that indicates an item cannot be used due to missing character stats	
> 	; Matches "Rarity: ..." + anything until "--------"\r\n
> 	If (RegExMatch(CBContents, "s)^(.+?:.+?\r\n)(.+?-{8}\r\n)(.*)", match)) {
> ```
> 
> Add this new line:
> 
> ```
> CBContents:= SubStr(CBContents, InStr(CBContents,"`n") + 1) 
> ```
> 
> Function should look like this with the new added line:
> 
> ```
> PreProcessContents(CBContents)
> {
> ; --- Place fixes for data inconsistencies here ---
> CBContents:= SubStr(CBContents, InStr(CBContents,"`n") + 1) ; <----- new
> 
> ; Remove the line that indicates an item cannot be used due to missing character stats	
> 	; Matches "Rarity: ..." + anything until "--------"\r\n
> 	If (RegExMatch(CBContents, "s)^(.+?:.+?\r\n)(.+?-{8}\r\n)(.*)", match)) {
> ```
> 
> Save file and restart POETradeMacro.

This worked for me. The other fix didn't.

**Comment by TridentRPG** [comment]
> > 
> 
> This worked for me. The other fix didn't.

Worked for me, as well!

**Comment by regara** [comment]
Also worked for me 

Emphasis on needing to restart it after

**Comment by TonZaga** [comment]
TL:DR - I'm getting a ParseMapTier: couldn't parse item data chunk when I try to Alt+D in game.

**Comment by louisphilipj** [comment]
![image](https://user-images.githubusercontent.com/89715789/131236116-0e349d71-8a08-4eb3-b36a-3c77ae02ef29.png)
