### ISSUE TITLE
can't choose tmpleague

### ISSUE THREAD

**Issue by renewkan** [PoE-TradeMacro/POE-TradeMacro#268]
I can't choose "tmpstandard" or "tmphardcore" when i choose it will be only standard.
but i can choose between "standard" and "hardcore"

**Comment by Eruyome** [comment]
Before I go further into this please take a look at this here https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/263, especially the last 3-4 comments. From your description only I can't say if it is the same or a different issue. The fix was to change to a default calendar instead of using hte buddhist calendar...

The league parsing failed to recognize an active temp league because the current date was translated to the year 2560. Ans the current date has to be between the temp league start and end date.

**Comment by renewkan** [comment]
omg I just change calendar and it work now ! 
lol after try a lot of thing including first half of [#263](https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/263) then scroll down to check that last comments.
feel very stupid right now.

**Comment by Eruyome** [comment]
Well, told you so :P

**Comment by Eruyome** [comment]
Now I also have to think of a way to warn the user in such a case, so far I don't know if I can detect the used calendar is not the "default".

**Comment by Eruyome** [comment]
Can you try the test script with your other calendar again while replacing this line 
`FormatTime, TimeStr, %UTCTimestamp%, %UTCFormatStr%`
with
`FormatTime, TimeStr, %UTCTimestamp%, %UTCFormatStr% LSys`

and see if the results are different, the new result the "correct" one?

**Comment by renewkan** [comment]
no different.
still same before change calendar.

**Comment by Eruyome** [comment]
`FormatTime, TimeStr, %UTCTimestamp%, %UTCFormatStr% LSys D4`

what about this?

**Comment by renewkan** [comment]
still no different.
but i notice that when i add LSys and save then re open script and edit to check that FormatTime again.
it doesn't have LSys anymore.
It supposed to be this way?

**Comment by Eruyome** [comment]
ohhh, thats wrong.
it shouldn't happen when you use the little test script I told you about, once saved it shouldn't change. it does happen when you add this code to trademacro by editing `_TradeMacroMain.ahk`

**Comment by renewkan** [comment]
look like i can edit it now.
but still no different.

**Comment by Eruyome** [comment]
Hm, may have to look into this a bit more at a later time. What calendar where you using btw?

**Comment by renewkan** [comment]
before i use my own region (thailand) 7/3/2560 and then change to english (united states) 3/7/2017

**Comment by Eruyome** [comment]
Good to know, I haven't fully understood all the options here yet https://autohotkey.com/docs/commands/FormatTime.htm. 

**Ln** and **Dn** so its probably possible to switch the calendar but unless someone figures this out for me it will have to wait a bit.

**Comment by pedrolucasmag** [comment]
Same problem here and I am using default calendar o.o

2017-03-07T16:06:23Z

**Comment by Braitaq** [comment]
I'm having the same problem after getting home from work today. It has worked fine over the weekend and yesterday but now its stuck on standard and wont save changing to temp league (no wonder the maps sold so fast :/ )

**Comment by Eruyome** [comment]
Fyi, the 2.0.3 update was messed up for everyone, but I just released that, it's now fixed. Normally the leagues work for (almost) everyone.

**Comment by Minomol** [comment]
Hey man I dl-ed the 2.0.4 yet as I run it, I get the notif about 2.0.4 being available, and current version shows 2.0.3 still

And the issue persists on my side still. I tried deleting all the script-created config files in my documents, but still.

**Comment by Eruyome** [comment]
yeah... the version thing was fixed.

**Comment by Minomol** [comment]
@Eruyome 
result: 2017-03-07T21:06:39z

**Comment by Eruyome** [comment]
That seems to be fine at first look. You probably have some different problem.

Can you try to describe the issue in detail? Does everything work as intended (selecting leagues, saving/loading settings) with the exception that the script always falls back to use `standard` or `hardcore` in the search?

**Comment by Minomol** [comment]
Basically yes, I select the "tmpstandard" value, press ok, open edit setting again and it's back at the default value. Editing the config files and reloading scripts doesn't seem to be affecting the selection.

**Comment by Eruyome** [comment]
The script works like this:
- Parse all leagues from GGG API, filter out SSF leagues
- Compare the current date with the star and end date of leagues to see if a temp league is currently active.
- The selection done by the user (settings) is never changed by the script BUT if a temp league is selected but none found (active) the script falls back to the permanent leagues.

You describe you change to tmpstandard, reopen settings and it's back at the defaults, but the default should be tmpstandard. Have you completely reinstalled the script, including removing the config files from the user settings folder?

**Comment by Minomol** [comment]
I found that the script places its config files in two places - my documents directly, and then my documents/PoE-TradeMacro

Not sure why it was in two places. Is there any other place where the config files might be located?

**Comment by Eruyome** [comment]
my documents/PoE-TradeMacro should be the only place

**Comment by Minomol** [comment]
FYI Just now downloaded the 2.0.6 and tmpstandard is working now for me. Cheers
