### ISSUE TITLE
Stuck on initializing script

### ISSUE THREAD

**Issue by Jordmondo** [PoE-TradeMacro/POE-TradeMacro#530]
Hey everytime I run the trade script it is stuck on initializing script and then goes 'not responding'. I can run the item info script fine but not the trade script. Any ideas? Thanks

**Comment by tabs-mc** [comment]
I've been having this issue for the last couple of weeks. Very occasionally if I leave it for 10 minutes it will work, usually however it just sits there 'initializing'.

Things I've tried without successs:

* Updating to 2.5.6
* Deleting all folders and reinstalling
* Checking windows firewall to see if AHK is blocked

POE Trade is running just fine for me via the browser. Running Item Info works just fine also.

**Comment by Eruyome** [comment]
Please check if the file `temp\StartupLog.txt` exists and post it contents here.

**Comment by Jordmondo** [comment]
Starting up PoE-TradeMacro....

----------------------------------------------------------
2017-09-29T06:35Z
----------------------------------------------------------

Requesting leagues from api.pathofexile.com...

cURL command:
"C:\Users\Jordan\Documents\AHK Scripts\POE-TradeMacro-2.5.6\lib\curl.exe" "http://api.pathofexile.com/leagues?type=main" -ILks -H "Host:api.pathofexile.com" -H "Connection:keep-alive" -H "Cache-Control:max-age=0" -H "Content-type:application/x-www-form-urlencoded; charset=UTF-8" -H "Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8" -H "User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36" --max-time 90 

Answer:
HTTP/1.1 302 Found
Server: nginx/1.8.1
Date: Fri, 29 Sep 2017 06:35:41 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: POESESSID=ee6a8dd4362edb1e299c513f314c1d81; path=/; domain=.pathofexile.com; HttpOnly
Location: /login/?redir=%2Fleagues%3Ftype%3Dmain
X-Frame-Options: SAMEORIGIN

HTTP/1.1 404
Server: nginx/1.8.1
Date: Fri, 29 Sep 2017 06:35:41 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: POESESSID=095d8576c3407bb248ffa85ac72cf9fc; path=/; domain=.pathofexile.com; HttpOnly



----------------------------------------------------------
2017-09-29T06:35Z
----------------------------------------------------------

Testing CloudFlare bypass, connecting to http://poe.trade...

cURL command:
"C:\Users\Jordan\Documents\AHK Scripts\POE-TradeMacro-2.5.6\lib\curl.exe" "http://poe.trade" -ILks -H "User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" -H "Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8" -H "Accept-Encoding:gzip, deflate" -H "Accept-Language:de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4" -H "Connection:keep-alive" -H "Host:poe.trade" -H "Upgrade-Insecure-Requests:1" --max-time 90 

Answer:
HTTP/1.1 200 OK
Date: Fri, 29 Sep 2017 06:35:43 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Set-Cookie: __cfduid=d84e4ed44ccecc19c7f3e7ec94a4cb2b51506666943; expires=Sat, 29-Sep-18 06:35:43 GMT; path=/; domain=.poe.trade; HttpOnly
X-Frame-Options: DENY
Content-Encoding: gzip
Server: cloudflare-nginx
CF-RAY: 3a5cec8a9421353c-LHR

**Comment by Eruyome** [comment]
That seems ok, does it always get stuck? How long do you usually wait?

**Comment by Jordmondo** [comment]
I've left it 10 mins max before getting bored of it and closing it through task manager. I can try longer I guess though I would have thought it should be almost instant maybe a few seconds most

**Comment by Eruyome** [comment]
That's way too long.
Anyway, I'll have to think about this later, you may be able to find where this gets stuck though by editing `resources\ahk\TradeMacroInit.ahk` and adding messageboxes between lines 31 - 213. At random places, something like 
```
MsgBox, 0x1010, Init Error, Place 1
...
MsgBox, 0x1010, Init Error, Place 2
...
MsgBox, 0x1010, Init Error, Place 3
```

to see which box gets executed last.

**Comment by Jordmondo** [comment]
Unfortunately tried the above and still stuck on same :(

**Comment by Calyx-** [comment]
I've also been having this issue for the past week, so I decided to do some debugging.

I'm not sure if you'll have the same issue, but mine seems to be caused by https://raw.githubusercontent.com/ not loading.

I've fixed this for now by copying the correct data file content for the blank files from https://github.com/PoE-TradeMacro/POE-TradeMacro/tree/master/data_trade and commenting out lines 207-209 in `resources\ahk\TradeMacroInit.ahk` to prevent it attempting to update these files.
```
;If (TradeOpts.DownloadDataFiles and not TradeOpts.Debug) {
;	TradeFunc_DownloadDataFiles()
;}
```

**Comment by Eruyome** [comment]
This should be partly fixed now, btw @Calyx- , there's a little trick to skip downloading those files, just enabled debug output in the settings menu. 
I've changed the cURL timeouts so while your requests still may fail it shouldn't take that long. I have added one request to raw.githubusercontent to the startup log so please show it to me.

**Comment by tabs-mc** [comment]
I still get this issue with 2.5.7
Been 'Initializing Script' for at least 5 minutes now.

Here is the log:
`Starting up PoE-TradeMacro....

----------------------------------------------------------
2017-10-02T11:30Z
----------------------------------------------------------

Requesting leagues from api.pathofexile.com...

cURL command:
"D:\POETrade 2.5.7\lib\curl.exe" "http://api.pathofexile.com/leagues?type=main" -ILks -H "Host:api.pathofexile.com" -H "Connection:keep-alive" -H "Cache-Control:max-age=0" -H "Content-type:application/x-www-form-urlencoded; charset=UTF-8" -H "Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8" -H "User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36" --max-time 30 

Answer:
HTTP/1.1 302 Found
Server: nginx/1.8.1
Date: Mon, 02 Oct 2017 11:30:00 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: POESESSID=9ef5f804f10a5643a5f01cd88d0e8e05; path=/; domain=.pathofexile.com; HttpOnly
Location: /login/?redir=%2Fleagues%3Ftype%3Dmain
X-Frame-Options: SAMEORIGIN

HTTP/1.1 404
Server: nginx/1.8.1
Date: Mon, 02 Oct 2017 11:30:00 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: POESESSID=ca76bb0c3e40ba8c832814f2180f5aba; path=/; domain=.pathofexile.com; HttpOnly



----------------------------------------------------------
2017-10-02T11:30Z
----------------------------------------------------------

Testing CloudFlare bypass, connecting to http://poe.trade...

cURL command:
"D:\POETrade 2.5.7\lib\curl.exe" "http://poe.trade" -ILks -H "User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" -H "Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8" -H "Accept-Encoding:gzip, deflate" -H "Accept-Language:de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4" -H "Connection:keep-alive" -H "Host:poe.trade" -H "Upgrade-Insecure-Requests:1" --max-time 30 

Answer:
HTTP/1.1 200 OK
Date: Mon, 02 Oct 2017 11:30:01 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Set-Cookie: __cfduid=d4dc4ea6baee9b488dadd005c2c0220581506943801; expires=Tue, 02-Oct-18 11:30:01 GMT; path=/; domain=.poe.trade; HttpOnly
X-Frame-Options: DENY
Content-Encoding: gzip
Server: cloudflare-nginx
CF-RAY: 3a7753c880dc3590-LHR



----------------------------------------------------------
2017-10-02T11:31Z
----------------------------------------------------------

Data file download from https://raw.githubusercontent.com/POE-TradeMacro/POE-TradeMacro/master/data_trade/...

cURL command:
"D:\POETrade 2.5.7\lib\curl.exe" "https://raw.githubusercontent.com/POE-TradeMacro/POE-TradeMacro/master/data_trade/boot_enchantment_mods.txt" -ILks --max-time 30 

Answer:


`

Calyx's fix worked for me with 2.5.6, no doubt it will for this version also.

**Comment by Eruyome** [comment]
There's an issue with Sky Broadband not being able to resolve the raw.githubusercontent.com domain, https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/537#issuecomment-333407187.

**Comment by Jordmondo** [comment]
That'll be the issue then! Will try the work around next opportunity

**Comment by Eruyome** [comment]
I'll close this and keep the other issue open to direct people there if they have the same issue.
