### ISSUE TITLE
ctrl+f on some map result in "Unknown Map"

### ISSUE THREAD

**Issue by zynaxsoft** [PoE-TradeMacro/POE-TradeMacro#607]
Some map such as Cage Map when using ctrl+f , it fills the search bar with "Unknown Map" "tier:3". Possibly because of the new maps?

**Comment by noname2tellu** [comment]
I was having a similar problem and decided to try and fix it. Got something to work, but I'm new to .ahk and stuff...

In POE-ItemInfo.ahk I replaced the line

` SubType = Unknown%A_Space%Map`

with
```	
			SubType := RegExMatch(LoopField, "\s.*Map", Match)
			SubType = %Match%
			
			If SubType in Map
			{
				SubType = %LoopField%
			}
```

Got it to work with a normal and 2 property magic Lookout Map, but I've got no idea when it will break / not work (again new to this sort of stuff).

**Comment by aRTy42** [comment]
The code does not need a change, the underlying data file needs to be updated with the new maps. I didn't do that right away because I wanted to wait for more data from the wiki and didn't remember that this function used the Subtype. In my mind the outdated part was the Ctrl+C info for maps and simply updating the map list without any additional infos would not have helped there.

**Comment by Eruyome** [comment]
While it's true what arty says, I implemented a hotfix that doesn't need updated data to search for the new map types. I'll close this.

**Comment by zynaxsoft** [comment]
Thank you for the hotfix!

However, it still does not work for me. I tried both updating the script and download the new release.

**Comment by Eruyome** [comment]
Could you edit `<TM folder>\resources\TradeMacro.ahk`?
Lines 763 - 765 shoud look like this

```
	If (TradeOpts.Debug) {
		;console.log(RequestParams)
	}	
```

change it to:

```
	If (TradeOpts.Debug) {
		;console.log(RequestParams)
		DebugPrintArray([Item, RequestParams])
	}	
```

then reload the macro and make a search on any new map. A window with some debug information should pop up, copy and paste the text ehre, preferrably wrapped in a code block, there's an editor option for that.
