### ISSUE TITLE
corrupt unique jewels not working

### ISSUE THREAD

**Issue by asdf337** [PoE-TradeMacro/POE-TradeMacro#862]
The program is currently not working with corrupt unique jewels, It searches for NOT corrupt jewels when CTRL D/CTRL ALT D'ing corrupt unique jewels.

**Comment by Eruyome** [comment]
fixed

**Comment by asdf337** [comment]
Still not working, add the option for jewels, not by overriding all items,
its a main option now. It should only be a check mark in advanced search
for corrupted jewels, which is where the problem is. Honestly it should be
able to do this by itself like it always has, what happened?

**Comment by Eruyome** [comment]
Maybe I misunderstood the issue, there certainly was one with the advanced search and corrupted jewels which is definitely fixed.

I'll take another look at all of this.

**Comment by asdf337** [comment]
Yeah it still is not working from my side here, I cant search for corrupted
jewels without going into the main configuration page and changing the
option in there every time I have to search for a corrupted jewel then turn
it back off again for the normal items, which is very tedious. Also the +1
totem on shields doesnt work properly on rare shield, it searches for
unique special stats instead of the new craft. thanks.

**Comment by Eruyome** [comment]
Can you press ctrl +c on the item and post your clipboard here (totem mod)?
I can get that info from somewhere else but want to be sure that my test data is correct.
