### ISSUE TITLE
ERROR: Request to poeprices.info timed out or returned an invalid response!

### ISSUE THREAD

**Issue by Yenqq** [PoE-TradeMacro/POE-TradeMacro#969]
_TEMPLATE_ (Remove the explanations here from your post) 

Make sure:
* That you have checked the Wiki/FAQ before creating any issue.
* That poe.trade/GGG's website don't have any issues if loading the script takes too long or failes.

Information to include:
* AHK (including 32/64bit) version if you have any kind of script errors.
* Windows version could be relevant.

Fill out everything that may be relevant and remove everything except these informations below:  

AHK version:
Windows version:

**Comment by Yenqq** [comment]
The problem is only when i CTRL+D Rare items, there is my log

#####
### Please post this log file below to https://www.pathofexile.com/forum/view-thread/1216141/.
### Try not to "spam" their thread if a few other reports with the same error description were posted in the last hours.
#####

Request and response:
{
    "added": {
        "browserUrl": "https://www.poeprices.info/api?l=Synthesis&i=UmFyaXR5OiBSYXJlDQpSdW5lIEJpbmQNClJ1c3RpYyBTYXNoDQotLS0tLS0tLQ0KUmVxdWlyZW1lbnRzOg0KTGV2ZWw6IDQ0DQotLS0tLS0tLQ0KSXRlbSBMZXZlbDogODENCi0tLS0tLS0tDQoxMyUgaW5jcmVhc2VkIEdsb2JhbCBQaHlzaWNhbCBEYW1hZ2UNCi0tLS0tLS0tDQorODkgdG8gQXJtb3VyDQorMTcgdG8gbWF4aW11bSBMaWZlDQorMjElIHRvIENoYW9zIFJlc2lzdGFuY2UNCjE0JSBpbmNyZWFzZWQgU3R1biBhbmQgQmxvY2sgUmVjb3ZlcnkNCg==&w=1",
        "encodedData": "UmFyaXR5OiBSYXJlDQpSdW5lIEJpbmQNClJ1c3RpYyBTYXNoDQotLS0tLS0tLQ0KUmVxdWlyZW1lbnRzOg0KTGV2ZWw6IDQ0DQotLS0tLS0tLQ0KSXRlbSBMZXZlbDogODENCi0tLS0tLS0tDQoxMyUgaW5jcmVhc2VkIEdsb2JhbCBQaHlzaWNhbCBEYW1hZ2UNCi0tLS0tLS0tDQorODkgdG8gQXJtb3VyDQorMTcgdG8gbWF4aW11bSBMaWZlDQorMjElIHRvIENoYW9zIFJlc2lzdGFuY2UNCjE0JSBpbmNyZWFzZWQgU3R1biBhbmQgQmxvY2sgUmVjb3ZlcnkNCg==",
        "encodingError": "",
        "league": "Synthesis",
        "requestUrl": "https://www.poeprices.info/api?l=Synthesis&i=UmFyaXR5OiBSYXJlDQpSdW5lIEJpbmQNClJ1c3RpYyBTYXNoDQotLS0tLS0tLQ0KUmVxdWlyZW1lbnRzOg0KTGV2ZWw6IDQ0DQotLS0tLS0tLQ0KSXRlbSBMZXZlbDogODENCi0tLS0tLS0tDQoxMyUgaW5jcmVhc2VkIEdsb2JhbCBQaHlzaWNhbCBEYW1hZ2UNCi0tLS0tLS0tDQorODkgdG8gQXJtb3VyDQorMTcgdG8gbWF4aW11bSBMaWZlDQorMjElIHRvIENoYW9zIFJlc2lzdGFuY2UNCjE0JSBpbmNyZWFzZWQgU3R1biBhbmQgQmxvY2sgUmVjb3ZlcnkNCg==",
        "retHeader": "502",
        "timeoutParam": 25
    }
}

**Comment by nadav-shemer** [comment]
Same here:
```
#####
### Please post this log file below to https://www.pathofexile.com/forum/view-thread/1216141/.
### Try not to "spam" their thread if a few other reports with the same error description were posted in the last hours.
#####

Request and response:
{
    "added": {
        "browserUrl": "https://www.poeprices.info/api?l=Synthesis&i=UmFyaXR5OiBSYXJlDQpCcmltc3RvbmUgV2FyZA0KSHVicmlzIENpcmNsZXQNCi0tLS0tLS0tDQpRdWFsaXR5OiArMjklIChhdWdtZW50ZWQpDQpFbmVyZ3kgU2hpZWxkOiAzNjEgKGF1Z21lbnRlZCkNCi0tLS0tLS0tDQpSZXF1aXJlbWVudHM6DQpMZXZlbDogNjkNCkludDogMTU0DQotLS0tLS0tLQ0KU29ja2V0czogQi1HLUItUiANCi0tLS0tLS0tDQpJdGVtIExldmVsOiA4NQ0KLS0tLS0tLS0NCldpbnRlciBPcmIgaGFzICsyIE1heGltdW0gU3RhZ2VzDQotLS0tLS0tLQ0KMTc3JSBpbmNyZWFzZWQgRW5lcmd5IFNoaWVsZA0KKzI1JSB0byBDb2xkIFJlc2lzdGFuY2UNCjE2JSBpbmNyZWFzZWQgU3R1biBhbmQgQmxvY2sgUmVjb3ZlcnkNCis0MiB0byBtYXhpbXVtIEVuZXJneSBTaGllbGQgKGNyYWZ0ZWQpDQotLS0tLS0tLQ0KU2hhcGVyIEl0ZW0NCg==&w=1",
        "encodedData": "UmFyaXR5OiBSYXJlDQpCcmltc3RvbmUgV2FyZA0KSHVicmlzIENpcmNsZXQNCi0tLS0tLS0tDQpRdWFsaXR5OiArMjklIChhdWdtZW50ZWQpDQpFbmVyZ3kgU2hpZWxkOiAzNjEgKGF1Z21lbnRlZCkNCi0tLS0tLS0tDQpSZXF1aXJlbWVudHM6DQpMZXZlbDogNjkNCkludDogMTU0DQotLS0tLS0tLQ0KU29ja2V0czogQi1HLUItUiANCi0tLS0tLS0tDQpJdGVtIExldmVsOiA4NQ0KLS0tLS0tLS0NCldpbnRlciBPcmIgaGFzICsyIE1heGltdW0gU3RhZ2VzDQotLS0tLS0tLQ0KMTc3JSBpbmNyZWFzZWQgRW5lcmd5IFNoaWVsZA0KKzI1JSB0byBDb2xkIFJlc2lzdGFuY2UNCjE2JSBpbmNyZWFzZWQgU3R1biBhbmQgQmxvY2sgUmVjb3ZlcnkNCis0MiB0byBtYXhpbXVtIEVuZXJneSBTaGllbGQgKGNyYWZ0ZWQpDQotLS0tLS0tLQ0KU2hhcGVyIEl0ZW0NCg==",
        "encodingError": "",
        "league": "Synthesis",
        "requestUrl": "https://www.poeprices.info/api?l=Synthesis&i=UmFyaXR5OiBSYXJlDQpCcmltc3RvbmUgV2FyZA0KSHVicmlzIENpcmNsZXQNCi0tLS0tLS0tDQpRdWFsaXR5OiArMjklIChhdWdtZW50ZWQpDQpFbmVyZ3kgU2hpZWxkOiAzNjEgKGF1Z21lbnRlZCkNCi0tLS0tLS0tDQpSZXF1aXJlbWVudHM6DQpMZXZlbDogNjkNCkludDogMTU0DQotLS0tLS0tLQ0KU29ja2V0czogQi1HLUItUiANCi0tLS0tLS0tDQpJdGVtIExldmVsOiA4NQ0KLS0tLS0tLS0NCldpbnRlciBPcmIgaGFzICsyIE1heGltdW0gU3RhZ2VzDQotLS0tLS0tLQ0KMTc3JSBpbmNyZWFzZWQgRW5lcmd5IFNoaWVsZA0KKzI1JSB0byBDb2xkIFJlc2lzdGFuY2UNCjE2JSBpbmNyZWFzZWQgU3R1biBhbmQgQmxvY2sgUmVjb3ZlcnkNCis0MiB0byBtYXhpbXVtIEVuZXJneSBTaGllbGQgKGNyYWZ0ZWQpDQotLS0tLS0tLQ0KU2hhcGVyIEl0ZW0NCg==",
        "retHeader": "502",
        "timeoutParam": 25
    }
}
```

**Comment by baislet518** [comment]
Same suddenly stoped working

**Comment by baislet518** [comment]
#####
### Please post this log file below to https://www.pathofexile.com/forum/view-thread/1216141/.
### Try not to "spam" their thread if a few other reports with the same error description were posted in the last hours.
#####

Request and response:
{
    "added": {
        "browserUrl": "https://www.poeprices.info/api?l=Synthesis&i=UmFyaXR5OiBSYXJlDQpPYmxpdmlvbiBTYW5jdHVhcnkNClZhYWwgU3Bpcml0IFNoaWVsZA0KLS0tLS0tLS0NClF1YWxpdHk6ICs4JSAoYXVnbWVudGVkKQ0KQ2hhbmNlIHRvIEJsb2NrOiAyNCUNCkVuZXJneSBTaGllbGQ6IDEwMSAoYXVnbWVudGVkKQ0KLS0tLS0tLS0NClJlcXVpcmVtZW50czoNCkxldmVsOiA2Mg0KSW50OiAxNTkNCi0tLS0tLS0tDQpTb2NrZXRzOiBCIA0KLS0tLS0tLS0NCkl0ZW0gTGV2ZWw6IDgxDQotLS0tLS0tLQ0KNSUgaW5jcmVhc2VkIFNwZWxsIERhbWFnZQ0KLS0tLS0tLS0NCiszOSB0byBJbnRlbGxpZ2VuY2UNCisxOCB0byBtYXhpbXVtIEVuZXJneSBTaGllbGQNCjM0JSBpbmNyZWFzZWQgRW5lcmd5IFNoaWVsZA0KKzI1JSB0byBMaWdodG5pbmcgUmVzaXN0YW5jZQ0KKzI1JSB0byBDaGFvcyBSZXNpc3RhbmNlDQoxNCUgaW5jcmVhc2VkIFN0dW4gYW5kIEJsb2NrIFJlY292ZXJ5DQo=&w=1",
        "encodedData": "UmFyaXR5OiBSYXJlDQpPYmxpdmlvbiBTYW5jdHVhcnkNClZhYWwgU3Bpcml0IFNoaWVsZA0KLS0tLS0tLS0NClF1YWxpdHk6ICs4JSAoYXVnbWVudGVkKQ0KQ2hhbmNlIHRvIEJsb2NrOiAyNCUNCkVuZXJneSBTaGllbGQ6IDEwMSAoYXVnbWVudGVkKQ0KLS0tLS0tLS0NClJlcXVpcmVtZW50czoNCkxldmVsOiA2Mg0KSW50OiAxNTkNCi0tLS0tLS0tDQpTb2NrZXRzOiBCIA0KLS0tLS0tLS0NCkl0ZW0gTGV2ZWw6IDgxDQotLS0tLS0tLQ0KNSUgaW5jcmVhc2VkIFNwZWxsIERhbWFnZQ0KLS0tLS0tLS0NCiszOSB0byBJbnRlbGxpZ2VuY2UNCisxOCB0byBtYXhpbXVtIEVuZXJneSBTaGllbGQNCjM0JSBpbmNyZWFzZWQgRW5lcmd5IFNoaWVsZA0KKzI1JSB0byBMaWdodG5pbmcgUmVzaXN0YW5jZQ0KKzI1JSB0byBDaGFvcyBSZXNpc3RhbmNlDQoxNCUgaW5jcmVhc2VkIFN0dW4gYW5kIEJsb2NrIFJlY292ZXJ5DQo=",
        "encodingError": "",
        "league": "Synthesis",
        "requestUrl": "https://www.poeprices.info/api?l=Synthesis&i=UmFyaXR5OiBSYXJlDQpPYmxpdmlvbiBTYW5jdHVhcnkNClZhYWwgU3Bpcml0IFNoaWVsZA0KLS0tLS0tLS0NClF1YWxpdHk6ICs4JSAoYXVnbWVudGVkKQ0KQ2hhbmNlIHRvIEJsb2NrOiAyNCUNCkVuZXJneSBTaGllbGQ6IDEwMSAoYXVnbWVudGVkKQ0KLS0tLS0tLS0NClJlcXVpcmVtZW50czoNCkxldmVsOiA2Mg0KSW50OiAxNTkNCi0tLS0tLS0tDQpTb2NrZXRzOiBCIA0KLS0tLS0tLS0NCkl0ZW0gTGV2ZWw6IDgxDQotLS0tLS0tLQ0KNSUgaW5jcmVhc2VkIFNwZWxsIERhbWFnZQ0KLS0tLS0tLS0NCiszOSB0byBJbnRlbGxpZ2VuY2UNCisxOCB0byBtYXhpbXVtIEVuZXJneSBTaGllbGQNCjM0JSBpbmNyZWFzZWQgRW5lcmd5IFNoaWVsZA0KKzI1JSB0byBMaWdodG5pbmcgUmVzaXN0YW5jZQ0KKzI1JSB0byBDaGFvcyBSZXNpc3RhbmNlDQoxNCUgaW5jcmVhc2VkIFN0dW4gYW5kIEJsb2NrIFJlY292ZXJ5DQo=",
        "retHeader": "502",
        "timeoutParam": 25
    }
}

**Comment by baislet518** [comment]
update it only happens with rare items

**Comment by rubsilence** [comment]
#####
### Please post this log file below to https://www.pathofexile.com/forum/view-thread/1216141/.
### Try not to "spam" their thread if a few other reports with the same error description were posted in the last hours.
#####

Request and response:
{
    "added": {
        "browserUrl": "https://www.poeprices.info/api?l=Standard&i=UmFyaXR5OiBSYXJlDQpDYXRhY2x5c20gQ2xvYWsNCkxhY3F1ZXJlZCBHYXJiDQotLS0tLS0tLQ0KRXZhc2lvbiBSYXRpbmc6IDUwOSAoYXVnbWVudGVkKQ0KRW5lcmd5IFNoaWVsZDogMTAwIChhdWdtZW50ZWQpDQotLS0tLS0tLQ0KUmVxdWlyZW1lbnRzOg0KTGV2ZWw6IDUyDQpEZXg6IDc2DQpJbnQ6IDc2DQotLS0tLS0tLQ0KU29ja2V0czogUi1HLUIgDQotLS0tLS0tLQ0KSXRlbSBMZXZlbDogNzANCi0tLS0tLS0tDQorMzAgdG8gSW50ZWxsaWdlbmNlDQo3OCUgaW5jcmVhc2VkIEV2YXNpb24gYW5kIEVuZXJneSBTaGllbGQNCis1OCB0byBtYXhpbXVtIE1hbmENCisxMCUgdG8gQ29sZCBSZXNpc3RhbmNlDQo=&w=1",
        "encodedData": "UmFyaXR5OiBSYXJlDQpDYXRhY2x5c20gQ2xvYWsNCkxhY3F1ZXJlZCBHYXJiDQotLS0tLS0tLQ0KRXZhc2lvbiBSYXRpbmc6IDUwOSAoYXVnbWVudGVkKQ0KRW5lcmd5IFNoaWVsZDogMTAwIChhdWdtZW50ZWQpDQotLS0tLS0tLQ0KUmVxdWlyZW1lbnRzOg0KTGV2ZWw6IDUyDQpEZXg6IDc2DQpJbnQ6IDc2DQotLS0tLS0tLQ0KU29ja2V0czogUi1HLUIgDQotLS0tLS0tLQ0KSXRlbSBMZXZlbDogNzANCi0tLS0tLS0tDQorMzAgdG8gSW50ZWxsaWdlbmNlDQo3OCUgaW5jcmVhc2VkIEV2YXNpb24gYW5kIEVuZXJneSBTaGllbGQNCis1OCB0byBtYXhpbXVtIE1hbmENCisxMCUgdG8gQ29sZCBSZXNpc3RhbmNlDQo=",
        "encodingError": "",
        "league": "Standard",
        "requestUrl": "https://www.poeprices.info/api?l=Standard&i=UmFyaXR5OiBSYXJlDQpDYXRhY2x5c20gQ2xvYWsNCkxhY3F1ZXJlZCBHYXJiDQotLS0tLS0tLQ0KRXZhc2lvbiBSYXRpbmc6IDUwOSAoYXVnbWVudGVkKQ0KRW5lcmd5IFNoaWVsZDogMTAwIChhdWdtZW50ZWQpDQotLS0tLS0tLQ0KUmVxdWlyZW1lbnRzOg0KTGV2ZWw6IDUyDQpEZXg6IDc2DQpJbnQ6IDc2DQotLS0tLS0tLQ0KU29ja2V0czogUi1HLUIgDQotLS0tLS0tLQ0KSXRlbSBMZXZlbDogNzANCi0tLS0tLS0tDQorMzAgdG8gSW50ZWxsaWdlbmNlDQo3OCUgaW5jcmVhc2VkIEV2YXNpb24gYW5kIEVuZXJneSBTaGllbGQNCis1OCB0byBtYXhpbXVtIE1hbmENCisxMCUgdG8gQ29sZCBSZXNpc3RhbmNlDQo=",
        "retHeader": "502",
        "timeoutParam": 25
    }
}

**Comment by Yenqq** [comment]
It is fixed. Thanks!

**Comment by russpoe** [comment]
Not fixed.  https://www.pathofexile.com/forum/view-thread/1216141/  Please see previous posts.
